### ISSUE TITLE
Mobile A11y Testing 11/1

### ISSUE THREAD

**Issue by lpalmaro** [PolymerElements/iron-a11y-announcer#10]
On Android with Talkback, the announcements are read 3 times aloud each. Is this intended?

**Comment by valdrinkoshi** [comment]
It seems to be a Talkback issue, I've tested on android with talkback and i get the text announced too many times http://jsbin.com/duxowaqoso/1/edit?html,output
Talkback will announce the text:
- 3 times if we change the content
- 2 times if we change aria-label

**Comment by valdrinkoshi** [comment]
Opened a bug here https://code.google.com/p/chromium/issues/detail?id=560599
Closing this issue for the time being.
